### ISSUE TITLE
Feature Request - Routing connections

### ISSUE THREAD

**Issue by kensaggy** [awslabs/pgbouncer-rr-patch#10]
Hi,

I thought a really helpful feature would be to reroute connections much like we can reroute queries.
For example, I could have several redshift clusters, and give my users a single entry point (that runs pgbouncer), they would attempt to connect to the entry point and based on my routing logic (python function) I could reroute their connection to the cluster of my choosing (transparent to the user).

If possible, the authentication should occur on the cluster that user has been redirected to that way there's no need for manual handling of a `userlist.txt`

Thoughts? I'd be happy to contribute somehow even though C isn't my strong-suite (to say the least), But pgbouncer really lacks in documentation, I have no idea where to start.. If someone could lead the way I'd gladly follow and help :)

**Comment by rstrahan** [comment]
Hi kensaggy, Can you explain a little more what you mean by 'routing connections', and what the benefit(s) would be compared to the connection pool based query routing mechanisms that pgbouncer-rr supports now?
Regarding authentication - I do agree that maintaining userlist.txt is an inconvenience. Pgbouncer itself does support an alternative method called 'auth_query', designed to retrieve the md5 password hash from a postgresql 'pg_shadow' table, but Redshift (for security reasons) does not permit queries against pg_shadow, so that mechanism doesn't work, and we are left with the userlist.txt method.

**Comment by kensaggy** [comment]
An example scenario is I have 2-3 clusters. I move databases between these clusters according to need (e.g. freeing up disk space, moving to Dense Compute vs. Dense Storage). I want to give users a single entry point to connect and send queries through and have some logic unit (e.g. python) be able to reroute those connections to the correct cluster (as well as rewrite queries if needed)... basically a MITM :)

**Comment by rstrahan** [comment]
Thanks for the example. However, unless I misunderstand your scenario, you can do that with pgbouncer-rr now, using a python routing function to return the dbname for the specific cluster you want the query to be sent to. You can also provide a separate rewrite function if you want to modify the query before it is sent through to your desired target cluster. 
Let me know if something is missing.

**Comment by kensaggy** [comment]
Yes, maybe you're right, but what's currently preventing me from using pgbouncer the most is the need to predefine all those database names and connections manually and in a hard-coded format as well as the users list. If the cluster address and connection details could be fetched from a python function that would be great, then the user credentials should be verified against the cluster I "redirected" the connection to.

Anywho, that's sort of what I envision... a bouncer/proxy that is completely configurable through the python functions (and that can be hooked up to some data store which holds information on what sits where, and all authentication is done against redshift itself)

**Comment by rstrahan** [comment]
Hi Ken, Thanks. 

I can't avoid the need to have the databases and users defined in the pgbouncer configuration, unfortunately. This requirement is inherited from pgbouncer itself, and would be non-trivial to change since it's inherent in the whole 'connection pooling' architecture.

But here are some thoughts that may or may not work for you:

- programmatically modify the config files (pgbouncer.ini / users.txt) to add/remove databases from the [databases] section, or to add/remove users from the users file? You can force pgbouncer-rr to reload the config files by connecting to it's console and sending a RELOAD command, or by sending a SIGHUP signal to the process. 

 - user auth_query to retrieve users from a db table: pgbouncer provides the ability to retrieve user lists from the target database using 'auth_query' (see https://pgbouncer.github.io/config.html) to pull username and md5 passwords from the pg_shadow table. Unfortunately, this doesn't work in RedShift (pgshadow is not accessable) however if you could, in theory, choose to maintain your own separate table listing usernames and md5 passwords, and use the auth_query mechanism to query that rather than pg_shadow, and thus avoid the need for users.txt. 

NOTE - neither of these options eliminates the need for you to maintain the user list, unfortunately.. They just give you alternative mechanisms.  

However - you could get creative! If you always sent your 'create user' or 'alter user' statement via pgbouncer-rr, you could catch them in the re-write function and, use use them to maintain your users list - either in users.txt, or in a separate database table that can be accessed by auth_query.  

Any of these approaches help? 

Bob

**Comment by kensaggy** [comment]
Hey Bob, thanks for your reply.

I figured it would be non-trivial to change, I looked through pgbouncer's code...

Your suggestions are very creative, but they seem they might be hard to maintain in the long run (having multiple copies of user details & passwords, sync issues, etc.).

I think maybe the best approach would be to just write a new tool for this that acts as a more simple protocol proxy with extensible rerouting/rewriting mechanism similar to pgbouner-rr-patch (which is awesome btw).

Thanks for the quick response! Good to see this project is being maintained :)
