### ISSUE TITLE
Installation error on Ubuntu

### ISSUE THREAD

**Issue by rmadiwaledba** [awslabs/pgbouncer-rr-patch#23]
I am trying to install pgbouncer-rr on ubuntu but I am facing issue on line number 6525
I have installed libcares still no luck.

Here is the error

`
checking whether to use c-ares for DNS lookups... auto
./configure: line 6525: syntax error near unexpected token `CARES,'
./configure: line 6525: `  PKG_CHECK_MODULES(CARES, libcares >= 1.6.0, use_cares=yes, use_cares=no)'
`

**Comment by rstrahan** [comment]
Hi @rmadiwaledba,
 
It looks like a problem related to building pgbouncer itself, rather than pgbouncer-rr. Can you try building pgbouncer (without the pgbouncer-rr patch applied) and if you can reproduce the issue, you can followup with the [pgbouncer ](https://github.com/pgbouncer/pgbouncer) community.

Alternatively, for now, can you use Amazon Linux / CentOs / RedHat?

**Comment by rmadiwaledba** [comment]
@rstrahan Thank you for the reply. I was able to install pgbouncer-rr on Ubuntu. To resolve above error I have installed package 'pkg-config'. Now installation is done without any error.
