### ISSUE TITLE
Why not a standalone fork of pgbouncer?

### ISSUE THREAD

**Issue by marcjay** [awslabs/pgbouncer-rr-patch#24]
Hi,

As others have alluded to in other Issues, the building process of checking out both pgbouncer and pgbouncer-rr-patch repositories and then applying the patch to the base is quite fragile and a-typical of most other github projects.

Is there a good reason why this repository does not exist as a fork of the original, such that it could be checked out and built standalone? I looked at the license (ISC) and it doesn't seem to prohibit this.

Even better, could there not be a PR to merge into the main PgBouncer project? 

Many thanks,

Marc

**Comment by rstrahan** [comment]
> Is there a good reason why this repository does not exist as a fork of the original, such that it could be checked out and built standalone?
  
Hi Marc, It's been a while, but as I recall it had to do with keeping the changes maximally isolated from the original in an effort to make it easier to isolate any problems, to easily take advantage of new versions of pgbouncer, and to apply the ASL to the patch code only.  

> checking out both pgbouncer and pgbouncer-rr-patch repositories and then applying the patch to the base is quite fragile
  
We could probably make it less fragile by specifying a validated commit of pgbouncer rather than always pulling from HEAD (with the downside that latest features/fixes would not automatically be incorporated). Anyway, please do log any problems you encounter with the current process, and we'll try to help if possible.

Cheers
Bob

**Comment by marcjay** [comment]
Hi @rstrahan,

Many thanks for the reply. Understood, thank you. I think it would be great to try to get this merged with the main project - the changes don't seem AWS-specific and could benefit the wider community. 

Thank you, will do.

Cheers,

Marc

**Comment by memory** [comment]
Probably worth noting that https://github.com/awslabs/pgbouncer-rr-patch/pull/73 removes the licensing restriction that would prevent this from being merged upstream.
